name: API Server CI

on:
  push:
    branches:
      - main
      - "releases/**"
      - "features/**"
    paths-ignore:
      - ".github/workflows/ml-server-ci.yml"
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: api-server

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - run: npm ci
      - run: npm test
